#!/bin/bash

## DEPENDENCIES

dependencies=("mpd" "mpc" "pulseaudio" "ncmpcpp")

check_dep()
{
 command -v $1 && echo "[✓ ] $1" || instala $1
}

instala()
{
command -v pacman && sudo pacman -S $1 || sudo apt install $1
}

for i in "${dependencies[@]}"
do
	check_dep "$i"
done

## PYTHON DEPENDENCIES ##

command -v pip3 || sudo pacman -S python-pip || sudo apt install python3-pip 

py_dep=("setuptools" "ueberzug")


for i in "${py_dep[@]}"
do
	sudo pip3 install "$i"
done

## CONFIG ##

[ -z "$XDG_CONFIG_HOME" ] && echo 'export XDG_CONFIG_HOME="$HOME/.config"' >> $HOME/.profile

# MPD

[ -f ~/.config/mpd ] && mv ~/.config/mpd ~/.config/mpd.old

echo "Generating mpd config"
mkdir -p ~/.config/mpd
cp -R src/mpd/ ~/.config/ -v

# NCMPCPP

[ -z ~/.config/ncmpcpp ] && mv ~/.config/ncmpcpp ~/.config/ncmpcpp.old

echo "Generating mpd config"
mkdir -p ~/.config/ncmpcpp
cp -R src/ncmpcpp/ ~/.config/ -v

## MAKING EXECUTABLE ##

chmod +x ~/.config/ncmpcpp/ncmpcpp-ueberzug
chmod +x ~/.config/ncmpcpp/ncmpcpp_cover_art.sh
ln ~/.config/ncmpcpp/ncmpcpp-ueberzug ~/.local/bin/mpw

cp src/music/"Darude - Sandstorm.mp3" ~/Music/
